config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root "articles#index"
  
  resources :articles do
    resources :comments
  end

  resources :categories do
    # match '/tasks/complete/:id' => 'tasks#complete', as: 'complete_task', via: :put 
    resources :tasks
    # get '/today' => 'tasks#today'
  end

  get '/today' => 'tasks#today'
end
                                                                                                          

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :name, presence:true, uniqueness:true
    validates :body, presence:true, length: { minimum: 10 } 

    has_many :comments
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, uniqueness: true, length: { minimum: 6 }

    has_many :tasks
end

app/models/comment.rb
class Comment < ApplicationRecord

    belongs_to :article
end

app/models/task.rb
class Task < ApplicationRecord
   
    validates :name, presence:true, uniqueness:true, length: { minimum: 6 } 
    validates :body, presence:true, length: { minimum: 10, maximum: 50 } 
    validates :task_date, presence:true
    
    belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @articles = Article.all.order("created_at ASC")
    end

    def show
        @article = Article.find(params[:id])
        @comments = @article.comments
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        
        if @article.save
            redirect_to articles_path
        else
            render :new
        end
    end

    
    def edit
        @article = Article.find(params[:id])
    end
        
    def update
        @article = Article.find(params[:id])

        if @article.update(article_params)
            redirect_to articles_path
        else
            render :edit
        end 
    end


    def destroy
        @article = Article.find(params[:id])
        @article.destroy
    
        redirect_to root_path
    end

    private

    def article_params
        params.require(:article).permit(:name, :body)
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  # before_action :set_category, only: [:show, :edit, :update, :destroy]
  
  def index
    @categories = Category.all 
    @today = Task.where(task_date:Date.today)
    # @tasks = @category.tasks
    # @today = []
    # @categories.each do |category|
    # ttoday = Task.where(task_date:Date.today())
    # @today += ttoday if ttoday  
  end


  def show
    @category = Category.find(params[:id])
    @tasks = @category.tasks
  end


  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
        
        if @category.save
            redirect_to categories_path
            # redirect_to @category
            flash[:notice] = "Category was successfully created."
        else
            render :new
        end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
        redirect_to category_path(@category)
        flash[:notice] = "Category was successfully updated."
    else
        render :edit
    end 
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:notice] = "Category was successfully deleted."
    redirect_to categories_path
  end

  
  private
   
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :get_article

    def index
        @comments = @article.comments
    end

    def new
        @comment = @article.comments.build
    end

    def create
        @comment = @article.comments.build(comment_params)
         if @comment.save
            redirect_to article_comment_path(@article.id, @comment.id)
        else
            render :new
        end
    end

    def show
        @comment = Comment.find(params[:id])
    end

    def edit
        @comment = Comment.find(params[:id])
    end

    def update
        @comment = Comment.find(params[:id])
        if @comment.update(comment_params)
            redirect_to article_comment_path(@article.id, @comment.id)
        end
    end


    def destroy
        @comment = Comment.find(params[:id]).destroy
        redirect_to article_path(@article.id)
    end

    private

    def get_article
        @article = Article.find(params[:article_id])
    end

    def comment_params
        params.require(:comment).permit(:body, :article_id)
    end  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :get_category, except: [:today]
  before_action :set_task, only: %i[ show edit update destroy ]
  
  def index
    @tasks = @category.tasks
  end

  
  def show
    # @task = Task.find(params[:id])
    @task = @category.tasks.find(params[:id])
  end

  
  def new
    @task = @category.tasks.build
  end

  # GET /tasks/1/edit
  def edit
 
    @task = @category.tasks.find(params[:id])
  end

  # POST /tasks or /tasks.json
  def create

    # byebug
    @task = @category.tasks.build(task_params)

     
    respond_to do |format|

      if @task.save
    #     # format.html { redirect_to @task, notice: "Task was successfully created." }
        format.html { redirect_to category_tasks_path(@category.id), notice: "Task was successfully created" }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end


  def update

    @task = Task.find(params[:id])
    
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to category_task_path(@category.id, @task.id), notice: "Task was successfully updated" }
        # format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        # format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    # @task = @category.tasks.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to category_path(@category.id), notice: "Task was successfully deleted" }
      format.json { head :no_content }
    end
  end

  def today
    @tasks = Task.where(task_date:Date.today)
    # task.task_date == Date.today
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    def get_category
      @category = Category.find(params[:category_id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:category_id, :name, :body, :task_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/articles/edit.html.erb
<div class='p-5'>
<%# <%= render "form", article: @article, url:article_path %> 
<%= form_with scope: :article, url: article_path, local: true, method: :patch do |f| %>
<h1>EDIT ARTICLE</h1>
<p>
    <% if @article.errors.any? %>
        <ul>
            <% @article.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    <% end %>
</p>

<p>
    <%= f.label :name %><br/>
    <%= f.text_field :name, class: 'w-full mt-2 mb-6 px-4 py-2 border rounded-lg text-gray-700 focus:outline-none focus:border-green-500' %>
</p>

<p>
    <%= f.label :body %><br/>
    <%= f.text_area :body, class: 'w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none h-3/5'%>
</p>

<p>
    <%= link_to '<< return', articles_path%>
    <%= f.submit 'Submit', class:'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full' %>  
</p>

<% end %>
</div>
<%# <%= render "form", article: @article, url:update_article_path %> 

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>
<div class="h-1/2 bg-white text-black m-5 py-5 px-10 rounded-md">
<%= link_to "Logout", destroy_user_session_path, method: :delete, class:"absolute top-5 right-5 bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded" %>

    <h1 class='text-2xl font-bold mb-8'>All Articles</h1>

    <table>
        <thead>
            <tr>
                <th class='pr-5'>ID</th>
                <th class='pr-5'>Name</th>
                <th class='pr-5'>Body</th>
                <th class='pr-5' colspan="3">Action</th>
            </tr>
        </thead>

        <tbody>
            <% @articles.each do |article| %>  
                <tr>
                    <td class='pr-5'><%= article.id %></td>
                    <td class='pr-5'><%= link_to article.name, article %></td>
                    <td class='pr-5'><%= article.body %></td>
                
                    <td><button class="bg-blue-500 p-1 text-white rounded"><%= link_to "Show", article_path(article) %></button></td>
                    <td><button class="bg-green-500 p-1 text-white rounded"><%= link_to "Edit", edit_article_path(article) %></button></td> 
                    <td><button class="bg-red-500 p-1 text-white rounded"><%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?" }%></button></td>
                </tr>
            <% end %>
        </tbody>
    </table>

    <button class="bg-yellow-500 hover:bg-yellow-700 text-white p-2 font-bold rounded">
        <%= link_to 'New Article', new_article_path %>
    </button>

</div>

app/views/articles/new.html.erb
<%# <%= render "form", article: @article, url:articles_path %>
<div class='p-5'>
<%= form_with model: @article, local: true do |f| %>
<h1> Create New Article </h1>
<p>
    <% if @article.errors.any? %>
        <ul>
            <% @article.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    <% end %>
</p>

<p>
    <%= f.label :name  %><br/>
    <%= f.text_field :name, class: 'w-full mt-2 mb-6 px-4 py-2 border rounded-lg text-gray-700 focus:outline-none focus:border-green-500' %>
</p>

<p>
    <%= f.label :body %><br/>
    <%= f.text_area :body, class: 'w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none h-3/5' %>
</p>

    <%= link_to '<< return', articles_path%>
    <%= f.submit 'Create new article', class:'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full'%>

<% end %> 
</div>

app/views/articles/show.html.erb
<div class='p-5'>
    <p><strong><%= @article.name %></strong></p>
    <p><%= @article.body %></p>
     
    </br>
    </br>
    <h2><strong><%= @article.comments.count %> comments </strong> </h2>
   
    
    
    <%= render 'comments/index', comments: @comments %>
    
    <h2><strong>Add a comment:</strong></h2>
    <%= render 'comments/form' %>
    
    </br>
    </br>
    <%= link_to '<< return to articles', articles_path%>
    <button class="bg-green-500 p-1 text-white hover:text-black rounded"><%= link_to "Edit article", edit_article_path(@article) %></button>
    <button class="bg-red-500 p-1 text-white hover:text-black rounded"><%= link_to "Delete article", article_path(@article), 
                                    method: :delete,
                                    data: { confirm: "Are you sure you want to delete this article?" }%></button>



</div>

app/views/categories/edit.html.erb
<%= form_with scope: :category, url: category_path, local: true, method: :patch do |f| %>
<h1> Edit Category </h1>
<p>
    <% if @category.errors.any? %>
        <ul>
            <% @category.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    <% end %>
</p>

<p>
    <%= f.label :name %><br/>
    <%= f.text_field :name%>
</p>

<%= link_to '<< return', category_path%>
<%= f.submit %>

<% end %> 

app/views/categories/index.html.erb
<div class="w-screen bg-gray-300 h-screen flex justify-items-center">
    <div class="h-auto bg-white text-black m-5 py-5 px-10 rounded-md">
        <h1 class='text-2xl text-center font-bold'>CATEGORIES</h1>
        <h3 class='text-center'> Select a category to view tasks </h3>
        <br/>
        <br/>
        <table class='w-full'>
            <thead>
                <tr>
                    <th>Category ID</th>
                    <th>Name</th>
                    <th colspan="3">Action</th>
                </tr>
            </thead>

            <tbody>
                <% @categories.each do |category| %>
                    <tr>
                        <td class='pr-8'><%= link_to category.id %></td>
                        <td class='pr-8'><%= link_to category.name %></td>
                        <td><button class="bg-blue-500 p-2 rounded"><%= link_to "Show", category_path(category) %></button></td>
                        <td><button class="bg-green-500 p-2 rounded"><%= link_to "Edit", edit_category_path(category) %></button></td>
                        <td><button class="bg-red-500 p-2 rounded"><%= link_to "Delete", category_path(category), method: :delete,data: { confirm: "Are you sure you want to delete this category?" }%><button></td>                                                                        
                    </tr>
                <% end %>
            </tbody>
        </table>
        
        <button class="bg-yellow-500 hover:bg-yellow-700 text-white p-2 font-bold rounded">
            <%= link_to 'New Category', new_category_path %>
        </button>
    </div>


    <div class="h-auto bg-white text-black m-5 py-5 px-10 rounded-md">
        <h1 class='text-2xl text-center font-bold'>TASKS FOR TODAY</h1>
        <p class='text-center'><%= DateTime.now.strftime('%a, %d/%b/%Y') %></p>
        <br>
        <br>
        
        <%# <%= render 'tasks/today', tasks: @tasks %> 
        <% if @today.any? %>
        <table>
            <thead>
            <tr>
            <th class='text-center'>Category</th>
                <th class='text-center'>Name</th>
                <th class='text-center'>Task date</th>
            </tr>
            </thead>

            <tbody>
            <% @today.each do |task| %>
                <tr>
                    <td class='text-center'><%= task.category_id %></td>
                    <td class='text-center'><%= link_to task.name , category_task_path(task.category_id, task) %></td>
                    <td class='text-center'><%= task.task_date %></td>  
            <% end %>  
            <% else %>
            <span>No tasks today :(</span>
            <% end%>
                </tr>
            </tbody>
        </table>
    </div>
</div>

app/views/categories/new.html.erb
<div class='p-5'>
    <%= form_with(model: @category) do |f| %>
    <h1 class='text-2xl'> Create New Category </h1>
    <p>
        <% if @category.errors.any? %>
            <ul>
                <% @category.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        <% end %>
    </p>

    <p>
        <%= f.label :name , class:"block text-gray-700 text-sm font-bold mb-2"%><br/>
        <%= f.text_field :name, class:"shadow appearance-none border rounded w-72 py-1 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </p>
    <br>
    <%= link_to '<< return', categories_path%>
    <%= f.submit class:"bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>

    <% end %> 
</div>

app/views/categories/show.html.erb
<div class="w-screen bg-gray-300 h-screen flex justify-items-center">
    <div class="h-auto bg-white text-black m-5 py-5 px-10 rounded-md">
        
        <p class='text-2xl'><strong>CATEGORY: </strong><%= @category.name %></p>
        <br>
            
            
        <%= render "tasks/index", tasks: @tasks %>
        <%# <%= link_to 'New Task', new_category_task_path(@category.id) %> 
       
    </div>

        <p class='absolute bottom-8 left-8'>
            <%= link_to '<< return', categories_path %>
            <%= link_to "Edit Category", edit_category_path(@category) %>
        </p>
        
</div>

app/views/comments/_form.html.erb
<%= form_with model:[@article, @article.comments.build ], local: true do |f| %>
   
    <p>
        <%# <%= f.label :body %> 
        <%= f.text_field :body, class: 'w-full mt-2 mb-6 px-4 py-2 border rounded-lg text-gray-700 focus:outline-none focus:border-green-500' %>
    </p>
        
        <%= f.submit 'Create comment', class:'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full' %>
<% end %> 

app/views/comments/_index.html.erb
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Body</th>
                <th class='pr-5' colspan="3">Action</th>
            </tr>

        </thead>

        <tbody>
            <% @comments.each do |comment| %>
                <tr>
                    <td><%= comment.id %></td>
                    <td><%= comment.body %></td>
                    <td><%= comment.created_at.strftime('%a, %m/%d/%Y, %I:%M%p') %></td>
                    <td><%= link_to 'Edit', edit_article_comment_path(@article.id, comment), class: 'text-blue-500' %></td>
                    <td><%= link_to 'Delete', article_comment_path(@article.id, comment), 
                                    method: :delete, 
                                    data: { confirm: 'Are you sure?'} , class: 'text-red-500' %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
    <%# <%= link_to '<< return', root_path %> 
    <%# <button class="bg-yellow-500 hover:bg-yellow-700 text-white p-2 font-bold rounded"> %>
    <%# <%= link_to 'New Comment', new_article_comment_path(@article) %> 
    <%# </button> %>

app/views/comments/_new.html.erb
<div class='p-5'>
    <%= form_with model:[@article, @comment], local: true do |f| %>
    <h1> Create New Comment </h1>
    

    <p>
        <%= f.label :body %><br/>
        <%= f.text_field :body, class: 'w-full mt-2 mb-6 px-4 py-2 border rounded-lg text-gray-700 focus:outline-none focus:border-green-500' %>
    </p>
        <%= link_to '<< return', article_comments_path %>
        <%= f.submit 'Create comment', class:'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full' %>
    <% end %> 
</div>

app/views/comments/edit.html.erb
<div class='p-5'>
    <%= form_with(model: [@article,@comment],  method: :put) do |f|%>
    <p>
        <% if @comment.errors.any? %>
            <ul>
                <% @comment.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        <% end %>
    </p>

    <p>
        <%= f.label :body%><br/>
        <%= f.text_field :body%>
    </p>

        <%= link_to '<< back', @comment.article%>
        <%= f.submit class:'bg-blue-500 hover:bg-blue-700 text-white font-bold p-2 rounded' %>
        
    <% end %>
</div>

app/views/comments/index.html.erb
<div class='p-5'>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Body</th>
            </tr>

        </thead>

        <tbody>
            <% @comments.each do |comment| %>
                <tr>
                    <td><%= comment.id %></td>
                    <td><%= comment.body %></td>
                    
                    
                </tr>
            <% end %>
        </tbody>
    </table>
    <%= link_to '<< return', root_path%>
    <button class="bg-yellow-500 hover:bg-yellow-700 text-white p-2 font-bold rounded">
    <%= link_to 'Add Comment', new_article_comment_path(@article) %>
    </button>
</div>

app/views/comments/new.html.erb
<div class='p-5'>
    <%= form_with model:[@article, @comment], local: true do |f| %>
    <h1> Create New Comment </h1>
    <p>
        <% if @comment.errors.any? %>
            <ul>
                <% @comment.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        <% end %>
    </p>

    <p>
        <%= f.label :body %><br/>
        <%= f.text_field :body, class: 'w-full mt-2 mb-6 px-4 py-2 border rounded-lg text-gray-700 focus:outline-none focus:border-green-500' %>
    </p>
        <%= link_to '<< return', article_comments_path %>
        <%= f.submit 'Create comment', class:'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full' %>
    <% end %> 
</div>

app/views/comments/show.html.erb
<div class='p-5'>
    <p><%= notice %></p>

    <p>
    <strong>Body:</strong>
    <%= @comment.body %>
    </p>

    <%= link_to '<< return to article', @comment.article %>
</div>

app/views/tasks/_index.html.erb
<p id="notice"><%= notice %></p>
<% if @category.tasks.any? %>

<div class='flex justify-between'>
  <p class='text-2xl'><strong> All Tasks</strong></p>
  <p><%= link_to 'New Task', new_category_task_path(@category) ,class:'text-lg underline' %></p>
</div>

<br>

<section class="container mx-auto p-6 font-mono">
  <div class="w-full mb-8 overflow-hidden rounded-lg shadow-lg">
    <div class="w-full overflow-x-auto">

      <table class="w-full">
        <thead>
          <tr class="text-md font-semibold tracking-wide text-left text-gray-900 bg-gray-100 uppercase border-b border-gray-600">
            <th class="px-4 py-3">Category</th>
            <th class="px-4 py-3">Name</th>
            <th class="px-4 py-3">Body</th>
            <th class="px-4 py-3">Task date</th>
            <%# <th class="px-4 py-3">Created at</th> %>
            <th class="px-4 py-3" colspan="4">Action</th>
          </tr>
        </thead>

        <tbody class="bg-white">
          <% @tasks.each do |task| %>
            <tr class="text-gray-700">
              <td class="text-center"><%= task.category_id %></td>
              <td><%= task.name %></td>
              <td><%= task.body %></td>
              <td><%= task.task_date %></td>
              <%# <td><%= task.created_at.strftime('%a, %m/%d/%Y, %I:%M%p') %>
              <td><%= link_to 'Show', category_task_path(@category.id, task)%></td>
              <td><%= link_to 'Edit', edit_category_task_path(@category.id, task) %></td>
              <td><%= link_to 'Delete', category_task_path(@category.id, task), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr> 
          <% end %>
        </tbody>
      </table>

<% else %>
  <h1>Congrats! no tasks yet :( </h1>
<% end %>
<br>
</div>

<%# Loop for tasks for today %>

<div class="h-auto bg-yellow-500 text-black m-5 py-5 px-10 rounded-md absolute top-0 right-0">
  <h1 class='text-2xl text-center font-bold'>TASKS FOR TODAY</h1>
  <p class='text-center'><%= DateTime.now.strftime('%a, %d/%b/%Y') %></p>
 
  <% if @tasks.where(task_date:Date.today).any? %>
  <br>
  <table>
    <thead>
      <tr>
        <th class='text-center'>Name</th>
        <th class='text-center'>Body</th>
        <th class='text-center'>Task date</th>
      </tr>
    </thead>

    <tbody>
    <% @tasks.each do |task| %>
      <% if task.task_date == Date.today %>
          <tr>
            <td class='text-center'><%= task.name %></td>
            <td class='text-center'><%= task.body %></td>
            <td class='text-center'><%= task.task_date %></td>  
      <% end %>  
    <% end %>  
          </tr>
    </tbody>
  </table>
  <% else %>
  <h1 class='text-center'>Congrats! no tasks yet :( </h1>
  <% end %>
 
</div>

app/views/tasks/edit.html.erb
<div class='p-5'>
<h1 class='font-bold text-lg'>EDIT TASK</h1>

<%= render 'form', task: @task %>

<%= link_to '<< Back', @task.category %>
<%# <%= link_to 'Back', category_path(@category.id) %> 
<%= link_to 'Show', category_task_path(@category.id, @task.id) %>

</div>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>
<% if @category.tasks.any? %>

<div class='flex justify-between'>
  <p class='text-2xl'><strong> All Tasks</strong></p>
  <%# <p><%= link_to 'New Task', new_category_task_path(@category) ,class:'text-lg underline' %>
</div>

<br>

<section class="container mx-auto p-6 font-mono">
  <div class="w-full mb-8 overflow-hidden rounded-lg shadow-lg">
    <div class="w-full overflow-x-auto">

      <table class="w-full">
        <thead>
          <tr class="text-md font-semibold tracking-wide text-left text-gray-900 bg-gray-100 uppercase border-b border-gray-600">
            <th class="px-4 py-3">Category</th>
            <th class="px-4 py-3">Name</th>
            <th class="px-4 py-3">Body</th>
            <th class="px-4 py-3">Task date</th>
            <%# <th class="px-4 py-3">Created at</th> %>
            <th class="px-4 py-3" colspan="4">Action</th>
          </tr>
        </thead>

        <tbody class="bg-white">
          <% @tasks.each do |task| %>
            <tr class="text-gray-700">
              <td class="text-center"><%= task.category_id %></td>
              <td><%= task.name %></td>
              <td><%= task.body %></td>
              <td><%= task.task_date %></td>
              <%# <td><%= task.created_at.strftime('%a, %m/%d/%Y, %I:%M%p') %>
              <td><%= link_to 'Show', category_task_path(@category.id, task)%></td>
              <td><%= link_to 'Edit', edit_category_task_path(@category.id, task) %></td>
              <td><%= link_to 'Delete', category_task_path(@category.id, task), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr> 
          <% end %>
        </tbody>
      </table>

<% else %>
  <h1>Congrats! no tasks yet :( </h1>
<% end %>
<br>
</div>

<%# Loop for tasks for today %>

<div class="h-auto bg-yellow-500 text-black m-5 py-5 px-10 rounded-md absolute top-0 right-0">
  <h1 class='text-2xl text-center font-bold'>TASKS FOR TODAY</h1>
  <p class='text-center'><%= DateTime.now.strftime('%a, %d/%b/%Y') %></p>
  
  <% if @tasks.any? %>
  <br>
  <table>
    <thead>
      <tr>
        <th class='text-center'>Name</th>
        <th class='text-center'>Body</th>
        <th class='text-center'>Task date</th>
      </tr>
    </thead>

    <tbody>
    <% @tasks.each do |task| %>
      <% if task.task_date == Date.today %>
          <tr>
            <td class='text-center'><%= task.name %></td>
            <td class='text-center'><%= task.body %></td>
            <td class='text-center'><%= task.task_date %></td>  
      <% end %>  
    <% end %>  
          </tr>
    </tbody>
  </table>
  <% else %>
  <h1 class='text-center'>Congrats! no tasks yet :( </h1>
  <% end %>
 
</div>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @task.category_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @task.body %>
</p>

<p>
  <strong>Task date:</strong>
  <%= @task.task_date %>
</p>

<%= link_to 'Edit', edit_category_task_path(@category, @task) %> |
<%= link_to 'Delete', category_task_path(@category, @task), method: :delete, data: { confirm: 'Are you sure?' } %></td> |
<%= link_to 'Back to categories', @task.category %> |
<%# <%= link_to 'Back', category_path(@category.id) %> 
<%= link_to 'Back to main', categories_path %>